#! /bin/bash
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install build-essential git htop -y
sudo apt-get install libssl-dev libgmp-dev libboost-chrono1.54-dev libboost-filesystem1.54-dev libboost-system1.54-dev libboost-program-options1.54-dev libboost-thread1.54-dev -y
wget http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
tar -xzvf db-4.8.30.NC.tar.gz
cd db-4.8.30.NC/build_unix
../dist/configure --enable-cxx
make
sudo make install
export BDB_INCLUDE_PATH="/usr/local/BerkeleyDB.4.8/include"
export BDB_LIB_PATH="/usr/local/BerkeleyDB.4.8/lib"
sudo ln -s /usr/local/BerkeleyDB.4.8/lib/libdb-4.8.so /usr/lib/libdb-4.8.so
sudo ln -s /usr/local/BerkeleyDB.4.8/lib/libdb_cxx-4.8.so /usr/lib/libdb_cxx-4.8.so
cd
git clone https://github.com/thbaumbach/primecoin.git xolominer
cd xolominer/src
make -f makefile.unix
sudo strip primeminer
sudo cp -f primeminer /usr/local/bin/
echo '#! /bin/bash' > run.sh
echo 'while true; do ./primeminer -pooluser=ARHdqAGQQgrn2rARNPnm4T6Z2weRCHyCYQ -poolip=176.34.128.129 -poolport=1337 -genproclimit=32 -poolpassword=helloworldtest -poolfee=1; sleep 1; done' >> run.sh
chmod +x run.sh
screen -d -m ./run.sh
